# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdb',
        ),
    ]
