# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='notes.Title'),
        ),
    ]
